language: ruby
rvm:
  - 2.1.10
env:
  - MEETUP_API_KEY=secret_key
script:
  - RAILS_ENV=test bundle exec rake --trace db:setup
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - RAILS_ENV=test bundle exec rake --trace db:test:prepare
  - RAILS_ENV=test bundle exec rake --trace
