development:
  adapter: postgresql
  database: cincyrb_development
  pool: 5
  min_messages: 'warning'
  encoding: utf8

staging:
  adapter: postgresql
  database: cincyrb_staging
  pool: 5
  min_messages: 'warning'
  encoding: utf8

test: &test
  adapter: postgresql
  database: cincyrb_test
  pool: 5
  min_messages: 'warning'
  encoding: utf8

cucumber:
  <<: *test
